from django.urls import path
from .views import *

urlpatterns = [
    path('Paradas', list_stops, name='list_stops'),
    path('Paradas/<int:id>', show_stop_info, name='show_stop_info'),
    path('Paradas/Linhas/<int:id>', lines_per_stop, name='lines_per_stop'),
    path('Paradas/new', new_stop, name='new_stop'),
    path('Paradas/update/<int:id>', update_stop, name='update_stop'),
    path('Paradas/delete/<int:id>', delete_stop, name='delete_stop'),
    path('Paradas/import', import_stops, name='import_stops'),
    path('Paradas/import_update', import_stops_update, name='import_stops_update'),
    path('Paradas/Proximas', nearby_stops, name='nearby_stops'),
    path('Linhas', list_lines, name='list_lines'),
    path('Linhas/<int:id>', show_line_info, name='show_line_info'),
    path('Linhas/Veiculos/<int:id>', vehicles_per_line, name='vehicles_per_line'),
    path('Linhas/new', new_line, name='new_line'),
    path('Linhas/update/<int:id>', update_line, name='update_line'),
    path('Linhas/removestops/<int:id>', remove_stop_from_line, name='remove_stop_from_line'),
    path('Linhas/delete/<int:id>', delete_line, name='delete_line'),
    path('Linhas/import', import_lines, name='import_lines'),
    path('Linhas/import_update', import_lines_update, name='import_lines_update'),
    path('Veiculos', list_vehicles, name='list_vehicles'),
    path('Veiculos/<int:id>', show_vehicle_info, name='show_vehicle_info'),
    path('Veiculos/new', new_vehicle, name='new_vehicle'),
    path('Veiculos/update/<int:id>', update_vehicle, name='update_vehicle'),
    path('Veiculos/delete/<int:id>', delete_vehicle, name='delete_vehicle'),
    path('Veiculos/import', import_vehicles, name='import_vehicles'),
    path('Veiculos/import_update', import_vehicles_update, name='import_vehicles_update'),
    path('Posicoes', list_positions, name='list_positions'),
    path('Posicoes/<int:id>', show_position_info, name='show_position_info'),
    path('Posicoes/new', new_position, name='new_position'),
    path('Posicoes/update/<int:id>', update_position, name='update_position'),
    path('Posicoes/delete/<int:id>', delete_position, name='delete_position'),
    path('Posicoes/import', import_positions, name='import_positions'),
    path('Posicoes/import_update', import_positions_update, name='import_positions_update'),
]
