# Generated by Django 3.0.8 on 2020-07-18 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(-90, message='Latitude menor que -90'), django.core.validators.MaxValueValidator(90, message='Latitude maior que 90')])),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180, message='Longitude menor que -180'), django.core.validators.MaxValueValidator(180, message='Longitude maior que 180')])),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=50)),
                ('LinhaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linha_veiculo', to='CRUD.Linha')),
            ],
        ),
        migrations.CreateModel(
            name='PosicaoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(-90, message='Latitude menor que -90'), django.core.validators.MaxValueValidator(90, message='Latitude maior que 90')])),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180, message='Longitude menor que -180'), django.core.validators.MaxValueValidator(180, message='Longitude maior que 180')])),
                ('VeiculoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Veiculo')),
            ],
        ),
        migrations.AddField(
            model_name='linha',
            name='Paradas',
            field=models.ManyToManyField(related_name='parada_linha', to='CRUD.Parada'),
        ),
    ]
