# Generated by Django 3.0.8 on 2020-07-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaoveiculo',
            name='VeiculoId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Veiculo'),
        ),
    ]
